# Generated by Django 5.0 on 2026-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('marker_markdown', models.TextField(blank=True, null=True)),
                ('marker_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Hochgeladen'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('error', 'Fehler')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
